# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170109_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('\u6807\u9898', models.CharField(max_length=70)),
                ('\u6b63\u6587', models.TextField()),
                ('\u521b\u5efa\u65f6\u95f4', models.DateTimeField(auto_now_add=True)),
                ('\u4fee\u6539\u65f6\u95f4', models.DateTimeField(auto_now_add=True)),
                ('\u6587\u7ae0\u72b6\u6001', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1)),
                ('\u6458\u8981', models.CharField(blank=True, help_text='\u53ef\u9009\uff0c\u5982\u679c\u4e3a\u7a7a\uff0c\u622a\u53d6\u6b63\u6587\u768454\u4e2a\u5b57\u7b26', max_length=54, null=True)),
                ('\u6d4f\u89c8\u91cf', models.PositiveIntegerField(default=0)),
                ('\u70b9\u8d5e\u6570', models.PositiveIntegerField(default=0)),
                ('\u7f6e\u9876', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='\u521b\u5efa\u65f6\u95f4',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 10, 10, 5, 45, 610000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='\u540d\u79f0',
            field=models.CharField(default='\u9ed8\u8ba4\u5206\u7c7b', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='\u4fee\u6539\u65f6\u95f4',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 10, 10, 6, 37, 841000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='\u521b\u5efa\u65f6\u95f4',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 10, 10, 6, 46, 548000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='\u540d\u79f0',
            field=models.CharField(default='\u9ed8\u8ba4\u6807\u7b7e', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e\u96c6\u5408'),
        ),
    ]
